;-----------------------------------------------------------;
; MMREGS.INC						    ;
; (C) 1992-93						    ;
; Texas Instruments Inc.				    ;
; By: Keith Larson					    ;
;     TMS320Cxx DSP Applications			    ;
;							    ;
; Contains a list of commonly used values		    ;
;-----------------------------------------------------------;
DRR	.set	0
DXR	.set	1
TIM	.set	2
PRD	.set	3
IMR	.set	4
GREG	.set	5

B0_D	.set	0200h
B0_P	.set	0FA00h
B1_D	.set	0400h
B1_P	.set	0FC00h
B2_D	.set	060h
B3_D	.set	0600h
B3_P	.set	0FE00h

; end of mmregs.inc
